// Post-build SEO generation. Runs after `vite build` (see package.json).
//
// GitHub Pages serves SPAs via a 404.html fallback, which returns HTTP 404 for
// deep links — so crawlers never index subpages. This script writes a real
// index.html per route (dist/publications/index.html, dist/cv/index.html) so
// Pages serves HTTP 200, each with route-specific title/description, canonical
// URL, Open Graph/Twitter tags, and JSON-LD. Also emits sitemap.xml.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE, ROUTES } from '../src/seo.js';
import { publications } from '../src/data/publications.js';
import { exhibitions } from '../src/data/exhibitions.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const template = readFileSync(join(dist, 'index.html'), 'utf8');

const BLOCK_RE = /<!-- SEO:BEGIN[\s\S]*?<!-- SEO:END -->/;
if (!BLOCK_RE.test(template)) {
  console.error('generate-seo: SEO:BEGIN/SEO:END markers not found in dist/index.html');
  process.exit(1);
}

const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// GitHub Pages 301s /publications -> /publications/ (directory index), so the
// canonical form for subroutes carries a trailing slash.
const canonicalOf = (path) => SITE.origin + (path === '/' ? '/' : `${path}/`);

const absImage = SITE.origin + SITE.image;

function externalUrl(pub) {
  const links = Object.values(pub.links);
  if (links.length === 0) return undefined; // JSON.stringify drops the url key
  return links.find((href) => href.startsWith('http')) ?? SITE.origin + links[0];
}

function jsonLdFor(path) {
  if (path === '/') {
    return {
      '@context': 'https://schema.org',
      '@type': 'Person',
      name: 'Nick (Seungheon) Oh',
      alternateName: ['Nick Oh', 'Seungheon Oh'],
      description:
        'Researcher at socius labs bridging cognitive science and machine intelligence.',
      email: 'mailto:nick.sh.oh@socius.org',
      knowsAbout: [
        'Cognitive science',
        'Metacognition',
        'Large language models',
        'Explainable AI',
        'Computational social science',
      ],
      jobTitle: 'Researcher',
      worksFor: { '@type': 'Organization', name: 'socius labs', url: 'https://socius.org' },
      alumniOf: {
        '@type': 'CollegeOrUniversity',
        name: 'London School of Economics and Political Science',
      },
      url: SITE.origin + '/',
      image: absImage,
      sameAs: [
        'https://github.com/nick-sh-oh',
        'https://x.com/nickshoh',
        'https://www.linkedin.com/in/nick-sh-oh/',
        'https://scholar.google.com/citations?user=L0tpB4EAAAAJ',
        'https://orcid.org/0009-0003-2575-5493',
        'https://rawlog.substack.com/',
        'https://socius.org',
      ],
    };
  }
  if (path === '/publications') {
    return {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'Publications by Nick Oh',
      itemListElement: publications.map((pub, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        item: {
          '@type': 'ScholarlyArticle',
          name: pub.title,
          author: pub.authors.map((name) => ({ '@type': 'Person', name })),
          datePublished: String(pub.year),
          url: externalUrl(pub),
        },
      })),
    };
  }
  if (path === '/exhibitions') {
    return {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'Exhibitions by Nick Oh',
      itemListElement: exhibitions.map((ex, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        item: {
          '@type': 'VisualArtwork',
          name: ex.title,
          creator: ex.creators.map((name) => ({ '@type': 'Person', name })),
          dateCreated: String(ex.year),
          award: ex.awards,
          image: ex.image ? SITE.origin + ex.image : undefined,
          url: externalUrl(ex),
        },
      })),
    };
  }
  return null;
}

function blockFor(route) {
  const url = canonicalOf(route.path);
  const img = SITE.origin + (route.image ?? SITE.image);
  const imgAlt = route.imageAlt ?? 'Portrait of Nick (Seungheon) Oh';
  const lines = [
    '<!-- SEO:BEGIN (generated by scripts/generate-seo.mjs) -->',
    `<title>${esc(route.title)}</title>`,
    `<meta name="description" content="${esc(route.description)}" />`,
    `<link rel="canonical" href="${url}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${esc(SITE.name)}" />`,
    `<meta property="og:title" content="${esc(route.title)}" />`,
    `<meta property="og:description" content="${esc(route.description)}" />`,
    `<meta property="og:url" content="${url}" />`,
    `<meta property="og:image" content="${img}" />`,
    `<meta property="og:image:alt" content="${esc(imgAlt)}" />`,
    `<meta name="twitter:card" content="${route.image ? 'summary_large_image' : 'summary'}" />`,
    `<meta name="twitter:site" content="${SITE.twitter}" />`,
    `<meta name="twitter:title" content="${esc(route.title)}" />`,
    `<meta name="twitter:description" content="${esc(route.description)}" />`,
    `<meta name="twitter:image" content="${img}" />`,
  ];
  const ld = jsonLdFor(route.path);
  if (ld) {
    // <-escape so the payload can never close the script tag early.
    lines.push(
      `<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, '\\u003c')}</script>`
    );
  }
  lines.push('<!-- SEO:END -->');
  return lines.join('\n    ');
}

for (const route of ROUTES) {
  const html = template.replace(BLOCK_RE, blockFor(route));
  const outDir = route.path === '/' ? dist : join(dist, route.path.slice(1));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'index.html'), html);
  console.log(`generate-seo: wrote ${route.path === '/' ? '' : route.path.slice(1) + '/'}index.html`);
}

const today = new Date().toISOString().slice(0, 10);
const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...ROUTES.map((r) =>
    [`  <url>`, `    <loc>${canonicalOf(r.path)}</loc>`, `    <lastmod>${today}</lastmod>`, `  </url>`].join('\n')
  ),
  '</urlset>',
  '',
].join('\n');
writeFileSync(join(dist, 'sitemap.xml'), sitemap);
console.log('generate-seo: wrote sitemap.xml');
